export interface Book {
  id: string;
  title: string;
  author: string;
  isbn?: string;
  description: string;
  spineColor: string;
  spineTextColor?: "light" | "dark";
  spineWidth?: "thin" | "normal" | "thick";
  rating?: 1 | 2 | 3 | 4 | 5;
  shelf?: number;
}

export const books: Book[] = [
  {
    id: "all-watched-over-by-machines-of-loving-grace-richard",
    title: "All Watched Over by Machines of Loving Grace",
    author: "Richard Brautigan",
    description: "Better than I expected.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 0,
  },
  {
    id: "the-alignment-problem-machine-learning-and-human-values-bria",
    title: "The Alignment Problem: Machine Learning and Human Values",
    author: "Brian  Christian",
    isbn: "9780393635829",
    description: "Better than I expected.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 0,
  },
  {
    id: "poslednja-vezirova-noc-konstantin",
    title: "Poslednja vezirova noc",
    author: "Konstantin Petrović",
    description: "Couldn't fully connect with this one.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 0,
  },
  {
    id: "the-courage-to-be-disliked-how-to-free-yourself-change-your-",
    title: "The Courage to Be Disliked: How to Free Yourself, Change Your Life and Achieve Real Happiness",
    author: "Ichiro Kishimi",
    description: "Some chapters worked, some didn't. Read in 2026.",
    spineColor: "#3A5A3A",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 3,
    shelf: 0,
  },
  {
    id: "muzej-nevinosti-orhan",
    title: "Muzej nevinosti",
    author: "Orhan Pamuk",
    isbn: "9788676661749",
    description: "Sat with me long after the last page.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 0,
  },
  {
    id: "hello-human-a-history-of-visual-communication-michael",
    title: "Hello Human: A History of Visual Communication",
    author: "Michael Horsham",
    isbn: "9780500023884",
    description: "Wanted to like this more than I did. Read in 2026.",
    spineColor: "#E89B3F",
    spineTextColor: "dark",
    spineWidth: "thick",
    rating: 1,
    shelf: 0,
  },
  {
    id: "sreca-je-navika-psihokibernetika-maksvel",
    title: "Sreca je navika- psihokibernetika",
    author: "MAKSVEL MOLC",
    isbn: "9785289835031",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 0,
  },
  {
    id: "build-an-unorthodox-guide-to-making-things-worth-making-tony",
    title: "Build: An Unorthodox Guide to Making Things Worth Making",
    author: "Tony Fadell",
    isbn: "9781787634114",
    description: "Quietly perfect.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 0,
  },
  {
    id: "the-epic-of-gilgamesh-anonymous",
    title: "The Epic of Gilgamesh",
    author: "Anonymous",
    isbn: "9780141026282",
    description: "The kind of book I lend out and never see again.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "thin",
    rating: 5,
    shelf: 0,
  },
  {
    id: "best-offer-wins-marisa",
    title: "Best Offer Wins",
    author: "Marisa Kashino",
    isbn: "9781250400543",
    description: "Fine. Not memorable.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 0,
  },
  {
    id: "rosso-istanbul-ferzan",
    title: "Rosso Istanbul",
    author: "Ferzan Özpetek",
    isbn: "9788804633464",
    description: "Wanted to like this more than I did. Read in 2025.",
    spineColor: "#E89B3F",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 1,
    shelf: 0,
  },
  {
    id: "gomora-roberto",
    title: "Gomora",
    author: "Roberto Saviano",
    isbn: "9788071859185",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#F1E4C7",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 0,
  },
  {
    id: "solving-product-design-exercises-questions-answers-artiom",
    title: "Solving Product Design Exercises: Questions & Answers",
    author: "Artiom Dashinsky",
    isbn: "9781977000422",
    description: "Better than I expected.",
    spineColor: "#D4A82A",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 4,
    shelf: 0,
  },
  {
    id: "think-and-grow-rich-napoleon",
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    description: "Decent. Wouldn't reread. Read in 2025.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 3,
    shelf: 0,
  },
  {
    id: "empire-of-ai-inside-the-reckless-race-for-total-domination-k",
    title: "Empire of AI: Inside the reckless race for total domination",
    author: "Karen Hao",
    isbn: "9781802064667",
    description: "Won me over in the last third. Read in 2025.",
    spineColor: "#8A6420",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 0,
  },
  {
    id: "palestine-joe",
    title: "Palestine",
    author: "Joe Sacco",
    isbn: "9781560974321",
    description: "Marked half the pages with little folded corners. Read in 2025.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 0,
  },
  {
    id: "un-estate-dopo-l-altra-every-summer-after-carley",
    title: "Un'estate dopo l'altra. Every Summer After",
    author: "Carley Fortune",
    description: "Predictable story and shallow characters. I read it only to practice reading Italian, I guess it served the purpose.",
    spineColor: "#D1453B",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 1,
    shelf: 0,
  },
  {
    id: "l-et-fragile-donatella",
    title: "L'età fragile",
    author: "Donatella Di Pietrantonio",
    isbn: "9788858444030",
    description: "Couldn't fully connect with this one.",
    spineColor: "#8A6420",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 0,
  },
  {
    id: "nikuda-ne-idem",
    title: "Nikuda ne idem",
    author: "Румена Бужаровска",
    isbn: "9788680830216",
    description: "Loved every page.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 1,
  },
  {
    id: "brief-answers-to-the-big-questions-stephen",
    title: "Brief Answers to the Big Questions",
    author: "Stephen W. Hawking",
    isbn: "9781984819192",
    description: "Fine. Not memorable.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 1,
  },
  {
    id: "ai-2041-ten-visions-for-our-future-kai-fu",
    title: "AI 2041: Ten Visions for Our Future",
    author: "Kai-Fu Lee",
    isbn: "9780593238295",
    description: "Won me over in the last third.",
    spineColor: "#5A2B17",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 1,
  },
  {
    id: "careless-people-a-cautionary-tale-of-power-greed-and-lost-id",
    title: "Careless People: A Cautionary Tale of Power, Greed, and Lost Idealism",
    author: "Sarah Wynn-Williams",
    isbn: "9781250391230",
    description: "Closed it and just sat there for a minute.",
    spineColor: "#D4A82A",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 1,
  },
  {
    id: "the-top-five-regrets-of-the-dying-a-life-transformed-by-the-",
    title: "The Top Five Regrets of the Dying: A Life Transformed by the Dearly Departing",
    author: "Bronnie Ware",
    description: "Held me up for a full weekend. Read in 2025.",
    spineColor: "#3A1F4D",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 1,
  },
  {
    id: "the-thinking-machine-jensen-huang-nvidia-and-the-world-s-mos",
    title: "The Thinking Machine: Jensen Huang, Nvidia, and the World's Most Coveted Microchip",
    author: "Stephen Witt",
    isbn: "9780593832691",
    description: "A bit slow in places but worth it. Read in 2025.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 4,
    shelf: 1,
  },
  {
    id: "pod-tu-im-suncem-miodrag",
    title: "Pod tuđim suncem",
    author: "Miodrag Majić",
    isbn: "9788610053357",
    description: "The kind of book I lend out and never see again. Read in 2025.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 1,
  },
  {
    id: "niko-nije-zaboravljen-i-ni-ega-se-ne-se-amo-mirjana",
    title: "Niko nije zaboravljen i ničega se ne sećamo",
    author: "Mirjana Drljević",
    isbn: "9788660840273",
    description: "Marked half the pages with little folded corners. Read in 2025.",
    spineColor: "#5DAA5A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 1,
  },
  {
    id: "code-dependent-living-in-the-shadow-of-ai-madhumita",
    title: "Code Dependent: Living in the Shadow of AI",
    author: "Madhumita Murgia",
    isbn: "9781250867391",
    description: "Incredibly important book to read in these times. Talks about the side of AI less talked about - data training and reinforcement learning and people who are actually doing the work for AI to work like 'magic'. It was humbling reading all the human stories and interviews the author did, and I personally loved that so many fighters for Ethical AI are female!",
    spineColor: "#F1E4C7",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 1,
  },
  {
    id: "100-things-every-designer-needs-to-know-about-people-susan",
    title: "100 Things Every Designer Needs to Know About People",
    author: "Susan M. Weinschenk",
    isbn: "9780321767530",
    description: "Finished out of stubbornness.",
    spineColor: "#D4A82A",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 2,
    shelf: 1,
  },
  {
    id: "to-ni-je-ljubav-ana",
    title: "Što (ni)je ljubav",
    author: "Ana Bučević",
    isbn: "9789537351533",
    description: "Fine. Not memorable. Read in 2025.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 3,
    shelf: 1,
  },
  {
    id: "elon-musk-walter",
    title: "Elon Musk",
    author: "Walter Isaacson",
    isbn: "9781982181284",
    description: "Another masterpiece by Isaacson!",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 1,
  },
  {
    id: "basic-ai-a-human-guide-to-artificial-intelligence-david",
    title: "Basic AI: A Human Guide to Artificial Intelligence",
    author: "David L. Shrier",
    isbn: "9781472148759",
    description: "Fine. Not memorable.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 1,
  },
  {
    id: "the-lean-startup-eric",
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "9780307887894",
    description: "On my read shelf, notes coming soon.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "normal",
    shelf: 1,
  },
  {
    id: "papaya-salad-elisa",
    title: "Papaya Salad",
    author: "Elisa Macellari",
    isbn: "9788832730593",
    description: "The most beautiful graphic novel I read so far.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 1,
  },
  {
    id: "internet-for-the-people-ben",
    title: "Internet for the People",
    author: "Ben Tarnoff",
    isbn: "9781839762024",
    description: "A great view into the history of internet, from the Marea pipes for WW2 puproses to Google, Facebook and Uber. It shows the impact internet had on the world in the last 3 decades, most of all how it changed the way we work and communicate. It follows the red line, from an idea of connection and liberation humanity, into transformation to pure capitalism and segregation of people into personalised data groups for selling and buying in, as the author calls it, ' the online shopping mall'. It's very nicely written, the only thing lacking are the solution ideas, which don't offer much hope or a...",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 4,
    shelf: 1,
  },
  {
    id: "hooked-how-to-build-habit-forming-products-nir",
    title: "Hooked: How to Build Habit-Forming Products",
    author: "Nir   Eyal",
    isbn: "9781591847786",
    description: "Three stars feels right.",
    spineColor: "#C84A2E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 1,
  },
  {
    id: "design-thinking-kako-da-stvarate-proizvode-koje-ljudi-zele-m",
    title: "Design Thinking: kako da stvarate proizvode koje ljudi zele",
    author: "Milovan; Jevtic Dekic",
    description: "Fine. Not memorable.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 1,
  },
  {
    id: "million-dollar-weekend-the-surprisingly-simple-way-to-launch",
    title: "Million Dollar Weekend: The Surprisingly Simple Way to Launch a 7-Figure Business in 48 Hours",
    author: "Noah Kagan",
    isbn: "9780593539774",
    description: "Underwhelmed, honestly. Read in 2024.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 2,
    shelf: 2,
  },
  {
    id: "nove-vite-danielle",
    title: "Nove vite",
    author: "Danielle Steel",
    isbn: "9788892744196",
    description: "Uno dei peggiori libri che abbia mai letto.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "thick",
    rating: 1,
    shelf: 2,
  },
  {
    id: "kilom-tre-z-ro-maud",
    title: "Kilomètre zéro",
    author: "Maud Ankaoua",
    isbn: "9782924720233",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#C84A2E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 2,
  },
  {
    id: "the-path-to-senior-product-designer-an-actionable-growth-pla",
    title: "The Path to Senior Product Designer: An Actionable Growth Plan for a UX Design Career",
    author: "Artiom Dashinsky",
    isbn: "9798856186924",
    description: "Held me up for a full weekend.",
    spineColor: "#D1453B",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 2,
  },
  {
    id: "the-millionaire-fastlane-crack-the-code-to-wealth-and-live-r",
    title: "The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime!",
    author: "M.J. DeMarco",
    isbn: "9780984358106",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 2,
  },
  {
    id: "you-deserve-good-gelato-kacie",
    title: "You Deserve Good Gelato",
    author: "Kacie Rose",
    isbn: "9780593840436",
    description: "On my read shelf, notes coming soon. Read in 2024.",
    spineColor: "#D4A82A",
    spineTextColor: "dark",
    spineWidth: "thin",
    shelf: 2,
  },
  {
    id: "biti-i-imati-promjenom-vibracije-do-financijske-slobode-ana",
    title: "Biti i imati (Promjenom vibracije do financijske slobode)",
    author: "Ana Bučević",
    description: "Read this one. Notes coming.",
    spineColor: "#3A1F4D",
    spineTextColor: "light",
    spineWidth: "thin",
    shelf: 2,
  },
  {
    id: "the-joy-of-being-selfish-why-you-need-boundaries-and-how-to-",
    title: "The Joy of Being Selfish: Why you need boundaries and how to set them",
    author: "Michelle Elman",
    isbn: "9781787396777",
    description: "A bit slow in places but worth it.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 4,
    shelf: 2,
  },
  {
    id: "nevazne-tacke-gledista-paolo",
    title: "Nevazne tacke gledista",
    author: "Paolo Sorrentino",
    description: "On my read shelf, notes coming soon. Read in 2024.",
    spineColor: "#7B1F1F",
    spineTextColor: "light",
    spineWidth: "normal",
    shelf: 2,
  },
  {
    id: "seven-and-a-half-lessons-about-the-brain-lisa",
    title: "Seven And A Half Lessons About The Brain",
    author: "Lisa Feldman Barrett",
    isbn: "9780358157144",
    description: "Read it twice. Will probably read it again.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 2,
  },
  {
    id: "the-fifth-agreement-miguel",
    title: "The Fifth Agreement",
    author: "Miguel Ruiz",
    isbn: "9781878424686",
    description: "A nice surprise. Read in 2024.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 4,
    shelf: 2,
  },
  {
    id: "when-coffee-kale-compete-become-great-at-making-products-peo",
    title: "When Coffee & Kale Compete: Become Great at Making Products People Will Buy",
    author: "Alan Klement",
    description: "Just didn't land. Read in 2024.",
    spineColor: "#3A5A3A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 2,
  },
  {
    id: "the-woman-in-me-britney",
    title: "The Woman in Me",
    author: "Britney Spears",
    isbn: "9781668009048",
    description: "Good in parts. Read in 2024.",
    spineColor: "#A8C4A2",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 3,
    shelf: 2,
  },
  {
    id: "hello-world-how-to-be-human-in-the-age-of-the-machine-hannah",
    title: "Hello World: How to be Human in the Age of the Machine",
    author: "Hannah Fry",
    description: "Decent. Wouldn't reread.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 3,
    shelf: 2,
  },
  {
    id: "kako-najlakse-pojesti-sopstveno-zdravlje-ana",
    title: "Kako najlakse pojesti sopstveno zdravlje",
    author: "Ana Gifing",
    isbn: "9788663030671",
    description: "Knjiga je u suštini reklama za praksu autora. Izgleda kao da je kolekcija nekih nepovezanih članaka, komentara njenih klijenata, nema ni glavu ni rep. Puna je informacija o tome kako je sve što jedemo loše (bukvalno meso, voće, povrće, masti, šećer, ne znam da li od vazduha da treba da živimo?). Ali evo do kraja knjige ne saznah odgovor na naslov knjige, šta to treba jesti. Možda treba uplatiti konsultacije kod autorke da bi vam otkrila šta je to, ali iz ove knjige sigurno ništa novo nećete naučiti.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 1,
    shelf: 2,
  },
  {
    id: "spare-prince",
    title: "Spare",
    author: "Prince Harry",
    isbn: "9780593593806",
    description: "Easy four stars.",
    spineColor: "#4A6F9C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 2,
  },
  {
    id: "moja-baba-zen-budista-sini-a",
    title: "Moja baba zen budista",
    author: "Siniša Ubović",
    description: "Just didn't land.",
    spineColor: "#5DAA5A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 2,
    shelf: 2,
  },
  {
    id: "steve-jobs-walter",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbn: "9781451648539",
    description: "The kind of book I lend out and never see again.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 2,
  },
  {
    id: "articulating-design-decisions-communicate-with-stakeholders-",
    title: "Articulating Design Decisions: Communicate with Stakeholders, Keep Your Sanity, and Deliver the Best User Experience",
    author: "Tom Greever",
    isbn: "9781491921562",
    description: "Goes back on my bookshelf, never to the donation pile. Read in 2023.",
    spineColor: "#3A1F4D",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 3,
  },
  {
    id: "start-with-why-how-great-leaders-inspire-everyone-to-take-ac",
    title: "Start with Why: How Great Leaders Inspire Everyone to Take Action",
    author: "Simon Sinek",
    isbn: "9781591842804",
    description: "Pleasant. Didn't love it, didn't hate it.",
    spineColor: "#F1E4C7",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 3,
    shelf: 3,
  },
  {
    id: "ivot-je-lijep-kad-se-ivjeti-zna-ana",
    title: "Život je lijep kad se živjeti zna",
    author: "Ana Bučević",
    isbn: "9789534904336",
    description: "Quietly excellent.",
    spineColor: "#B8523A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 3,
  },
  {
    id: "the-four-agreements-a-practical-guide-to-personal-freedom-mi",
    title: "The Four Agreements: A Practical Guide to Personal Freedom",
    author: "Miguel Ruiz",
    isbn: "9781878424501",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#C84A2E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 3,
  },
  {
    id: "rich-dad-poor-dad-what-the-rich-teach-their-kids-about-money",
    title: "Rich Dad Poor Dad: What the Rich Teach Their Kids About Money—That the Poor and Middle Class Do Not!",
    author: "Robert T. Kiyosaki",
    isbn: "9780751532715",
    description: "Recommended this one to a few people already. Read in 2023.",
    spineColor: "#3A5A3A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 3,
  },
  {
    id: "emotional-design-why-we-love-or-hate-everyday-things-donald",
    title: "Emotional Design: Why We Love (or Hate) Everyday Things",
    author: "Donald A. Norman",
    isbn: "9780465051366",
    description: "Quietly perfect.",
    spineColor: "#B8523A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 3,
  },
  {
    id: "the-5-am-club-own-your-morning-elevate-your-life-robin",
    title: "The 5 AM Club: Own Your Morning. Elevate Your Life",
    author: "Robin Sharma",
    isbn: "9781443456630",
    description: "Wanted to like this more than I did.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 3,
  },
  {
    id: "don-t-make-me-think-revisited-a-common-sense-approach-to-web",
    title: "Don't Make Me Think, Revisited: A Common Sense Approach to Web Usability (Voices That Matter)",
    author: "Steve Krug",
    isbn: "9780321965516",
    description: "Read this one. Notes coming. Read in 2022.",
    spineColor: "#E89B3F",
    spineTextColor: "dark",
    spineWidth: "normal",
    shelf: 3,
  },
  {
    id: "conversations-with-god-an-uncommon-dialogue-book-3-neale",
    title: "Conversations With God: An Uncommon Dialogue, Book 3",
    author: "Neale Donald Walsch",
    isbn: "9781571741035",
    description: "Finished out of stubbornness.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 2,
    shelf: 3,
  },
  {
    id: "designing-for-emotion-aaron",
    title: "Designing for Emotion",
    author: "Aaron Walter",
    isbn: "9781937557003",
    description: "Worth the time.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 3,
  },
  {
    id: "moja-mama-zna-ta-se-de-ava-u-gradovima-radmila",
    title: "Moja mama zna šta se dešava u gradovima",
    author: "Radmila Petrović",
    isbn: "9788681360101",
    description: "A favourite. Read in 2022.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 3,
  },
  {
    id: "nice-girls-don-t-get-the-corner-office-101-unconscious-mista",
    title: "Nice Girls Don't Get the Corner Office: 101 Unconscious Mistakes Women Make That Sabotage Their Careers",
    author: "Lois P. Frankel",
    isbn: "9780446693318",
    description: "Read this one. Notes coming.",
    spineColor: "#5DAA5A",
    spineTextColor: "light",
    spineWidth: "normal",
    shelf: 3,
  },
  {
    id: "razgovori-s-bogom-1-neale",
    title: "Razgovori s Bogom 1",
    author: "Neale Donald Walsch",
    isbn: "9788683909759",
    description: "Quietly excellent.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 3,
  },
  {
    id: "the-richest-man-in-babylon-george",
    title: "The Richest Man in Babylon",
    author: "George S. Clason",
    isbn: "9780451205360",
    description: "Recommended this one to a few people already.",
    spineColor: "#A8C4A2",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 4,
    shelf: 3,
  },
  {
    id: "the-source-the-secrets-of-the-universe-the-science-of-the-br",
    title: "The Source: The Secrets of the Universe, the Science of the Brain",
    author: "Tara Swart",
    isbn: "9780062935731",
    description: "Won me over in the last third.",
    spineColor: "#8A6420",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 3,
  },
  {
    id: "voli-me-vi-e-od-svega-na-svijetu-mira",
    title: "Voli me više od svega na svijetu",
    author: "Mira Furlan",
    isbn: "9789533583754",
    description: "Felt like the author wrote this just for me.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 3,
  },
  {
    id: "ari-kako-je-balkanski-kokainski-kartel-osvojio-evropu-stevan",
    title: "Šarić - kako je balkanski kokainski kartel osvojio Evropu",
    author: "Stevan Dojčinović",
    isbn: "9788679634030",
    description: "Fine. Not memorable. Read in 2021.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 3,
    shelf: 3,
  },
  {
    id: "emotional-intelligence-why-it-can-matter-more-than-iq-daniel",
    title: "Emotional Intelligence: Why It Can Matter More Than IQ",
    author: "Daniel Goleman",
    isbn: "9780553804911",
    description: "Good in parts. Read in 2021.",
    spineColor: "#4A6F9C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 3,
  },
  {
    id: "gomorrah-a-personal-journey-into-the-violent-international-e",
    title: "Gomorrah: A Personal Journey Into the Violent International Empire of Naples' Organized Crime System",
    author: "Roberto Saviano",
    isbn: "9780312427795",
    description: "Sat with me long after the last page.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 4,
  },
  {
    id: "nonostante-tutto-jordi",
    title: "Nonostante tutto",
    author: "Jordi Lafebre",
    isbn: "9788832735680",
    description: "Couldn't fully connect with this one.",
    spineColor: "#5A2B17",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 2,
    shelf: 4,
  },
  {
    id: "la-mia-seconda-generazione-saghar",
    title: "La mia seconda generazione",
    author: "Saghar Khaleghpour",
    isbn: "9788807551642",
    description: "Loved every page. Read in 2024.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 4,
  },
  {
    id: "emotions-freedom-from-anger-jealousy-and-fear-osho",
    title: "Emotions: Freedom from Anger, Jealousy and Fear",
    author: "Osho",
    isbn: "9781938755927",
    description: "Pleasant. Didn't love it, didn't hate it. Read in 2023.",
    spineColor: "#F1E4C7",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 3,
    shelf: 4,
  },
  {
    id: "the-leader-who-had-no-title-a-modern-fable-on-real-success-i",
    title: "The Leader Who Had No Title: A Modern Fable on Real Success in Business and in Life",
    author: "Robin Sharma",
    isbn: "9781439109120",
    description: "Wanted to like this more than I did.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 1,
    shelf: 4,
  },
  {
    id: "invisible-cities-italo",
    title: "Invisible Cities",
    author: "Italo Calvino",
    isbn: "9780156453806",
    description: "Closed it and just sat there for a minute. Read in 2022.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 4,
  },
  {
    id: "the-diary-of-a-young-girl-anne",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    description: "Read this one. Notes coming.",
    spineColor: "#F1E4C7",
    spineTextColor: "dark",
    spineWidth: "normal",
    shelf: 4,
  },
  {
    id: "the-power-of-now-a-guide-to-spiritual-enlightenment-eckhart",
    title: "The Power of Now: A Guide to Spiritual Enlightenment",
    author: "Eckhart Tolle",
    description: "Couldn't fully connect with this one.",
    spineColor: "#C84A2E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 4,
  },
  {
    id: "the-girl-who-kicked-the-hornet-s-nest-stieg",
    title: "The Girl Who Kicked the Hornet’s Nest",
    author: "Stieg Larsson",
    isbn: "9780307269997",
    description: "Read this one. Notes coming.",
    spineColor: "#3A5A3A",
    spineTextColor: "light",
    spineWidth: "thin",
    shelf: 4,
  },
  {
    id: "the-girl-who-played-with-fire-stieg",
    title: "The Girl Who Played with Fire",
    author: "Stieg Larsson",
    isbn: "9780307269980",
    description: "On my read shelf, notes coming soon.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "thin",
    shelf: 4,
  },
  {
    id: "ana-karenina-leo",
    title: "Ana Karenina",
    author: "Leo Tolstoy",
    isbn: "9789561313880",
    description: "On my read shelf, notes coming soon.",
    spineColor: "#7B1F1F",
    spineTextColor: "light",
    spineWidth: "normal",
    shelf: 4,
  },
  {
    id: "prodigal-genius-the-life-of-nikola-tesla-john",
    title: "Prodigal Genius: The Life of Nikola Tesla",
    author: "John J. O'Neill",
    isbn: "9781596057135",
    description: "Read this one. Notes coming. Read in 2021.",
    spineColor: "#E89B3F",
    spineTextColor: "dark",
    spineWidth: "normal",
    shelf: 4,
  },
  {
    id: "how-to-speak-machine-computational-thinking-for-the-rest-of-",
    title: "How to Speak Machine: Computational Thinking for the Rest of Us",
    author: "John Maeda",
    isbn: "9780593086322",
    description: "Wanted to like this more than I did. Read in 2021.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 4,
  },
  {
    id: "the-power-of-vulnerability-teachings-of-authenticity-connect",
    title: "The Power of Vulnerability: Teachings of Authenticity, Connections and Courage",
    author: "Brené Brown",
    description: "Quietly excellent. Read in 2021.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 4,
  },
  {
    id: "atomic-habits-an-easy-proven-way-to-build-good-habits-break-",
    title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    author: "James Clear",
    description: "More than the sum of its chapters. Read in 2021.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 4,
    shelf: 4,
  },
  {
    id: "blindness-jos",
    title: "Blindness",
    author: "José Saramago",
    description: "A favourite.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 4,
  },
  {
    id: "by-the-river-piedra-i-sat-down-and-wept-paulo",
    title: "By the River Piedra I Sat Down and Wept",
    author: "Paulo Coelho",
    description: "Not for me, but glad I tried it. Read in 2021.",
    spineColor: "#7B1F1F",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 1,
    shelf: 4,
  },
  {
    id: "catch-the-rabbit-lana",
    title: "Catch the Rabbit",
    author: "Lana Bastašić",
    isbn: "9781529039603",
    description: "The kind of book I lend out and never see again.",
    spineColor: "#5DAA5A",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 4,
  },
  {
    id: "gdy-s-o-ce-by-o-bogiem-zenon",
    title: "Gdy słońce było bogiem",
    author: "Zenon Kosidowski",
    description: "One of the best things I read in 2021.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "like-the-flowing-river-paulo",
    title: "Like the Flowing River",
    author: "Paulo Coelho",
    isbn: "9780007235803",
    description: "Read it twice. Will probably read it again.",
    spineColor: "#9C2451",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "love-in-the-time-of-cholera-gabriel",
    title: "Love in the Time of Cholera",
    author: "Gabriel García Márquez",
    isbn: "9781400034680",
    description: "Sat with me long after the last page.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 5,
    shelf: 5,
  },
  {
    id: "memories-of-my-melancholy-whores-vintage-international-gabri",
    title: "Memories of My Melancholy Whores (Vintage International)",
    author: "Gabriel García Márquez",
    isbn: "9781400095940",
    description: "Easy four stars. Read in 2021.",
    spineColor: "#4A6F9C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 5,
  },
  {
    id: "mlije-ni-zubi-lana",
    title: "Mliječni zubi",
    author: "Lana Bastašić",
    isbn: "9789958305337",
    description: "One of those books I'm glad I read slowly.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "one-hundred-years-of-solitude-gabriel",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    description: "One of the best things I read in 2021.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "permanent-record-edward",
    title: "Permanent Record",
    author: "Edward Snowden",
    isbn: "9781250237231",
    description: "The kind of book I lend out and never see again.",
    spineColor: "#8A6420",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "pride-and-prejudice-jane",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9781441341709",
    description: "Reread-worthy.",
    spineColor: "#6B4FA8",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "the-4-hour-workweek-timothy",
    title: "The 4-Hour Workweek",
    author: "Timothy Ferriss",
    isbn: "9780307353139",
    description: "Smart and warm.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "thick",
    rating: 4,
    shelf: 5,
  },
  {
    id: "the-alchemist-paulo",
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "Held me up for a full weekend.",
    spineColor: "#3A1F4D",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 5,
  },
  {
    id: "the-art-of-loving-erich",
    title: "The Art of Loving",
    author: "Erich Fromm",
    isbn: "9780061129735",
    description: "Quietly perfect. Read in 2021.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "thick",
    rating: 5,
    shelf: 5,
  },
  {
    id: "the-little-prince-antoine",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    isbn: "9780152023980",
    description: "Recommended this one to a few people already.",
    spineColor: "#A8C4A2",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 4,
    shelf: 5,
  },
  {
    id: "the-subtle-art-of-not-giving-a-f-ck-a-counterintuitive-appro",
    title: "The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life",
    author: "Mark Manson",
    isbn: "9798804636129",
    description: "Underwhelmed, honestly. Read in 2019.",
    spineColor: "#7A4A8A",
    spineTextColor: "light",
    spineWidth: "thick",
    rating: 2,
    shelf: 5,
  },
  {
    id: "learning-from-las-vegas-the-forgotten-symbolism-of-architect",
    title: "Learning from Las Vegas: The Forgotten Symbolism of Architectural Form",
    author: "Robert Venturi",
    isbn: "9780262720069",
    description: "Marked half the pages with little folded corners.",
    spineColor: "#3F7A8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "radical-cities-across-latin-america-in-search-of-a-new-archi",
    title: "Radical Cities: Across Latin America in Search of a New Architecture",
    author: "Justin McGuirk",
    isbn: "9781781682807",
    description: "A favourite. Read in 2019.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 5,
  },
  {
    id: "vox-christina",
    title: "Vox",
    author: "Christina Dalcher",
    isbn: "9780440000785",
    description: "Couldn't fully connect with this one.",
    spineColor: "#C84A2E",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 1,
    shelf: 5,
  },
  {
    id: "yes-is-more-an-archicomic-on-architectural-evolution-bjarke",
    title: "Yes is More: An Archicomic on Architectural Evolution",
    author: "Bjarke Ingels Group",
    isbn: "9788799298808",
    description: "Glad I picked this up.",
    spineColor: "#1E2A47",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 5,
  },
  {
    id: "a-clash-of-kings-george",
    title: "A Clash of Kings",
    author: "George R.R. Martin",
    description: "Some chapters worked, some didn't. Read in 2016.",
    spineColor: "#3A5A3A",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 3,
    shelf: 5,
  },
  {
    id: "angels-demons-dan",
    title: "Angels & Demons",
    author: "Dan    Brown",
    isbn: "9781416524793",
    description: "Just didn't land.",
    spineColor: "#5DAA5A",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 1,
    shelf: 6,
  },
  {
    id: "animal-farm-george",
    title: "Animal Farm",
    author: "George Orwell",
    description: "Most underlined book of 2016.",
    spineColor: "#5A2B17",
    spineTextColor: "light",
    spineWidth: "thin",
    rating: 5,
    shelf: 6,
  },
  {
    id: "captive-prince-c-s",
    title: "Captive Prince",
    author: "C.S. Pacat",
    description: "Sat with me long after the last page.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "captive-prince-volume-two-c-s",
    title: "Captive Prince: Volume Two",
    author: "C.S. Pacat",
    description: "Closed it and just sat there for a minute.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "harry-potter-and-the-sorcerer-s-stone-j-k",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    isbn: "9780439554930",
    description: "One of those books I'm glad I read slowly.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "kings-rising-c-s",
    title: "Kings Rising",
    author: "C.S. Pacat",
    isbn: "9781743484951",
    description: "Goes back on my bookshelf, never to the donation pile. Read in 2016.",
    spineColor: "#5A2B17",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "perfume-the-story-of-a-murderer-patrick",
    title: "Perfume: The Story of a Murderer",
    author: "Patrick Süskind",
    description: "Quietly excellent. Read in 2016.",
    spineColor: "#B8523A",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 6,
  },
  {
    id: "the-catcher-in-the-rye-j-d",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "9780316769174",
    description: "Wanted to like this more than I did.",
    spineColor: "#F2C14E",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 2,
    shelf: 6,
  },
  {
    id: "the-fault-in-our-stars-john",
    title: "The Fault in Our Stars",
    author: "John  Green",
    description: "Couldn't fully connect with this one. Read in 2016.",
    spineColor: "#5A2B17",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 2,
    shelf: 6,
  },
  {
    id: "the-fellowship-of-the-ring-j-r-r",
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    isbn: "9780618346257",
    description: "A favourite.",
    spineColor: "#D4A82A",
    spineTextColor: "dark",
    spineWidth: "thick",
    rating: 5,
    shelf: 6,
  },
  {
    id: "the-girl-with-the-dragon-tattoo-stieg",
    title: "The Girl With the Dragon Tattoo",
    author: "Stieg Larsson",
    isbn: "9780670069019",
    description: "If I had to pick a desert-island shelf, this is on it.",
    spineColor: "#3A1F4D",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "the-great-gatsby-f",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "Worth the time.",
    spineColor: "#1F4D8C",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 6,
  },
  {
    id: "the-hunger-games-suzanne",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    isbn: "9780439023481",
    description: "Fine. Not memorable. Read in 2016.",
    spineColor: "#0F4D3F",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 3,
    shelf: 6,
  },
  {
    id: "the-lovely-bones-alice",
    title: "The Lovely Bones",
    author: "Alice Sebold",
    isbn: "9780316166683",
    description: "Held me up for a full weekend. Read in 2016.",
    spineColor: "#D1453B",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 6,
  },
  {
    id: "the-titan-s-curse-rick",
    title: "The Titan’s Curse",
    author: "Rick Riordan",
    description: "A nice surprise.",
    spineColor: "#2E5E4E",
    spineTextColor: "light",
    spineWidth: "normal",
    rating: 4,
    shelf: 6,
  },
  {
    id: "to-kill-a-mockingbird-harper",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780060935467",
    description: "Loved every page.",
    spineColor: "#E8B4C4",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 5,
    shelf: 6,
  },
  {
    id: "wuthering-heights-emily",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description: "Recommended this one to a few people already.",
    spineColor: "#A8C4A2",
    spineTextColor: "dark",
    spineWidth: "normal",
    rating: 4,
    shelf: 6,
  },
];

export function coverUrl(book: Book): string | null {
  if (!book.isbn) return null;
  return `https://covers.openlibrary.org/b/isbn/${book.isbn}-M.jpg`;
}
